import Head from "next/head";
import dynamic from "next/dynamic";

const Scene = dynamic(() => import("../src/components/three/Scene"), {
  ssr: false,
});

export default function Page() {
  return (
    <>
      <Head>
        <title>cc_r3f</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Scene />
    </>
  );
}
